# This is a basic workflow to help you get started with Actions

name:  Teste workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   teste_job:
    name: Executando job de teste 
    runs-on:  linux-amd64 #Definição do runner aqui, aqui pega a ultima versão do ubuntu, 
    steps:  #os steps são os passos parar execução do workflow, é dentro do steps que é aninhado os stesp para executar
    - name: Step 1 #Definição do nome da primeira step
      uses: actions/checkout@v2 #Uses é uma diretiva que faz parte da steps, Nesta linha está sendo feito com a action checkou o checkout para baixar os arquivos, neste caso é usado a versão 2 pode ser vista em @V2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: 'pedrolucascruz'
        password:  ${{ secrets.MINHACHAVE }}

    - name: Build and push Docker images
 
      uses: docker/build-push-action@v5.1.0
      with:
        cotext: .
        tags: 'pedrolucascruz/teste2:latest'
        push: true

